name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * 1'  # 每周运行一次
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth:

    - name: Sync upstream
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote add upstream https://github.com/coolsnowwolf/lede.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push origin master